language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"

script:
    - nosetests -s

after_success:
    - pip install coveralls
    - coverage run --source=otpauth setup.py -q nosetests
    - coveralls

notifications:
    email: false
